fix: compile regex pattern redundantly when parsing kafka version(#2662)
IBM/sarama pull request #2663
Opened 2023-10-08 13:05 UTC by qshuai

Fix compiling regular pattern redundantly to optimize CPU usage.

2023-10-10 13:35 UTC, Gorgonx7 requested changes

2023-10-10 13:35 UTC, Gorgonx7 commented on utils.go
> +	validKafkaVersion1 = regexp.MustCompile(`^0\.\d+\.\d+\.\d+$`)
Thanks for raising this, I think we could probably be a bit more clear with the variable names here and probably should just add a comment
```suggestion
        //This regex validates that a string complies with the pre kafka 1.0.0 format for version strings, for example 0.11.0.3
	validPreKafka1Version = regexp.MustCompile(`^0\.\d+\.\d+\.\d+$`)
```

2023-10-10 13:35 UTC, Gorgonx7 commented on utils.go
> +	validKafkaVersion2 = regexp.MustCompile(`^\d+\.\d+\.\d+$`)
```suggestion
        //This regex validates that a string complies with the post Kafka 1.0.0 format, for example 1.0.0
	validPostKafka1Version = regexp.MustCompile(`^\d+\.\d+\.\d+$`)
```

2023-10-10 13:35 UTC, Gorgonx7 commented on utils.go
> +		err = scanKafkaVersion(s, validKafkaVersion1, "0.%d.%d.%d", [3]*uint{&minor, &veryMinor, &patch})
```suggestion
		err = scanKafkaVersion(s, validPreKafka1Version, "0.%d.%d.%d", [3]*uint{&minor, &veryMinor, &patch})
```

2023-10-10 13:35 UTC, Gorgonx7 commented on utils.go
> +		err = scanKafkaVersion(s, validKafkaVersion2, "%d.%d.%d", [3]*uint{&major, &minor, &veryMinor})
```suggestion
		err = scanKafkaVersion(s, validPostKafka1Version, "%d.%d.%d", [3]*uint{&major, &minor, &veryMinor})
```

2023-10-11 05:26 UTC, qshuai commented
@Gorgonx7 Thanks! I have push a new commit fixing these issues

2023-10-11 09:33 UTC, dnwe approved these changes
Thanks for submitting this, changes look good to me

2023-10-11 11:15 UTC, merged